// <auto-generated />
using System;
using FSH.Modules.Avicola.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FSH.Starter.Migrations.PostgreSQL.Avicola
{
    [DbContext(typeof(AvicolaDbContext))]
    [Migration("20260625151816_AvicolaPreparacion")]
    partial class AvicolaPreparacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("avicola")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FSH.Modules.Avicola.Domain.Despacho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("Cantidad");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("ClienteId");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Fecha");

                    b.Property<Guid>("LoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("LoteId");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("Notas");

                    b.Property<decimal>("PesoTotalKg")
                        .HasColumnType("numeric")
                        .HasColumnName("PesoTotalKg");

                    b.Property<decimal?>("PrecioPorKg")
                        .HasColumnType("numeric")
                        .HasColumnName("PrecioPorKg");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("LoteId");

                    b.ToTable("Despachos", "avicola");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("FSH.Modules.Avicola.Domain.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .HasColumnType("text")
                        .HasColumnName("ContentType");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Fecha");

                    b.Property<Guid?>("FileAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("FileAssetId");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NombreArchivo");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("Notas");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("Origen");

                    b.Property<Guid?>("OrigenId")
                        .HasColumnType("uuid")
                        .HasColumnName("OrigenId");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("Tipo");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Url");

                    b.HasKey("Id");

                    b.HasIndex("Origen", "OrigenId");

                    b.ToTable("Documentos", "avicola");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("FSH.Modules.Avicola.Domain.Galpon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer")
                        .HasColumnName("Capacidad");

                    b.Property<string>("Codigo")
                        .HasColumnType("text")
                        .HasColumnName("Codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("Notas");

                    b.Property<decimal?>("SuperficieM2")
                        .HasColumnType("numeric")
                        .HasColumnName("SuperficieM2");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("text")
                        .HasColumnName("Ubicacion");

                    b.HasKey("Id");

                    b.ToTable("Galpones", "avicola");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("FSH.Modules.Avicola.Domain.Lote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CantidadInicial")
                        .HasColumnType("integer")
                        .HasColumnName("CantidadInicial");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Codigo");

                    b.Property<decimal?>("CostoPolluelo")
                        .HasColumnType("numeric")
                        .HasColumnName("CostoPolluelo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("Estado");

                    b.Property<DateTimeOffset>("FechaIngreso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaIngreso");

                    b.Property<DateTimeOffset?>("FechaSalidaPrevista")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaSalidaPrevista");

                    b.Property<DateTimeOffset?>("FechaSalidaReal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaSalidaReal");

                    b.Property<Guid?>("GalponId")
                        .HasColumnType("uuid")
                        .HasColumnName("GalponId");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("Notas");

                    b.Property<decimal?>("PesoInicialGramos")
                        .HasColumnType("numeric")
                        .HasColumnName("PesoInicialGramos");

                    b.Property<Guid?>("ProveedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("ProveedorId");

                    b.Property<string>("Raza")
                        .HasColumnType("text")
                        .HasColumnName("Raza");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("GalponId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Lotes", "avicola");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("FSH.Modules.Avicola.Domain.MovimientoContable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("Categoria");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Concepto");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Fecha");

                    b.Property<decimal>("Importe")
                        .HasColumnType("numeric")
                        .HasColumnName("Importe");

                    b.Property<Guid?>("LoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("LoteId");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("Notas");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("Tipo");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.HasIndex("LoteId");

                    b.HasIndex("Tipo");

                    b.ToTable("Movimientos", "avicola");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("FSH.Modules.Avicola.Domain.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric")
                        .HasColumnName("Cantidad");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Codigo");

                    b.Property<decimal?>("CostoEstimado")
                        .HasColumnType("numeric")
                        .HasColumnName("CostoEstimado");

                    b.Property<decimal?>("CostoReal")
                        .HasColumnType("numeric")
                        .HasColumnName("CostoReal");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("Descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("Estado");

                    b.Property<DateTimeOffset>("FechaPedido")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaPedido");

                    b.Property<DateTimeOffset?>("FechaRecepcion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaRecepcion");

                    b.Property<Guid?>("GalponId")
                        .HasColumnType("uuid")
                        .HasColumnName("GalponId");

                    b.Property<Guid?>("LoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("LoteId");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("Notas");

                    b.Property<Guid?>("ProveedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("ProveedorId");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("Tipo");

                    b.Property<string>("Unidad")
                        .HasColumnType("text")
                        .HasColumnName("Unidad");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("GalponId");

                    b.HasIndex("LoteId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Pedidos", "avicola");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("FSH.Modules.Avicola.Domain.PreparacionNave", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CamaNueva")
                        .HasColumnType("boolean")
                        .HasColumnName("CamaNueva");

                    b.Property<decimal?>("Costo")
                        .HasColumnType("numeric")
                        .HasColumnName("Costo");

                    b.Property<bool>("Desinfeccion")
                        .HasColumnType("boolean")
                        .HasColumnName("Desinfeccion");

                    b.Property<bool>("Desinsectacion")
                        .HasColumnType("boolean")
                        .HasColumnName("Desinsectacion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("Estado");

                    b.Property<DateTimeOffset?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaFin");

                    b.Property<DateTimeOffset>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaInicio");

                    b.Property<DateTimeOffset?>("FechaRetiro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaRetiro");

                    b.Property<Guid>("GalponId")
                        .HasColumnType("uuid")
                        .HasColumnName("GalponId");

                    b.Property<bool>("Lavado")
                        .HasColumnType("boolean")
                        .HasColumnName("Lavado");

                    b.Property<Guid?>("LoteAnteriorId")
                        .HasColumnType("uuid")
                        .HasColumnName("LoteAnteriorId");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("Notas");

                    b.Property<bool>("RetiradaCama")
                        .HasColumnType("boolean")
                        .HasColumnName("RetiradaCama");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("GalponId");

                    b.HasIndex("LoteAnteriorId");

                    b.ToTable("Preparaciones", "avicola");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("FSH.Modules.Avicola.Domain.RegistroAlimentacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CantidadKg")
                        .HasColumnType("numeric")
                        .HasColumnName("CantidadKg");

                    b.Property<decimal?>("CostoUnitario")
                        .HasColumnType("numeric")
                        .HasColumnName("CostoUnitario");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Fecha");

                    b.Property<Guid>("LoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("LoteId");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("Notas");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoAlimento")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("TipoAlimento");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.ToTable("Alimentacion", "avicola");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("FSH.Modules.Avicola.Domain.RegistroMortalidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("Cantidad");

                    b.Property<string>("Causa")
                        .HasColumnType("text")
                        .HasColumnName("Causa");

                    b.Property<int?>("Descartes")
                        .HasColumnType("integer")
                        .HasColumnName("Descartes");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Fecha");

                    b.Property<Guid>("LoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("LoteId");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("Notas");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.ToTable("Mortalidad", "avicola");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("FSH.Modules.Avicola.Domain.RegistroPeso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CantidadMuestra")
                        .HasColumnType("integer")
                        .HasColumnName("CantidadMuestra");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Fecha");

                    b.Property<Guid>("LoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("LoteId");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("Notas");

                    b.Property<decimal>("PesoPromedioGramos")
                        .HasColumnType("numeric")
                        .HasColumnName("PesoPromedioGramos");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.ToTable("Pesos", "avicola");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("FSH.Modules.Avicola.Domain.RegistroSanitario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Costo")
                        .HasColumnType("numeric")
                        .HasColumnName("Costo");

                    b.Property<string>("Dosis")
                        .HasColumnType("text")
                        .HasColumnName("Dosis");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Fecha");

                    b.Property<Guid>("LoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("LoteId");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("Notas");

                    b.Property<string>("Producto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Producto");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("Tipo");

                    b.Property<string>("ViaAplicacion")
                        .HasColumnType("text")
                        .HasColumnName("ViaAplicacion");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.ToTable("Sanidad", "avicola");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("FSH.Modules.Avicola.Domain.Despacho", b =>
                {
                    b.HasOne("FSH.Modules.Avicola.Domain.Lote", null)
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("FSH.Modules.Avicola.Domain.Lote", b =>
                {
                    b.HasOne("FSH.Modules.Avicola.Domain.Galpon", null)
                        .WithMany()
                        .HasForeignKey("GalponId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("FSH.Modules.Avicola.Domain.MovimientoContable", b =>
                {
                    b.HasOne("FSH.Modules.Avicola.Domain.Lote", null)
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("FSH.Modules.Avicola.Domain.Pedido", b =>
                {
                    b.HasOne("FSH.Modules.Avicola.Domain.Galpon", null)
                        .WithMany()
                        .HasForeignKey("GalponId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FSH.Modules.Avicola.Domain.Lote", null)
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("FSH.Modules.Avicola.Domain.PreparacionNave", b =>
                {
                    b.HasOne("FSH.Modules.Avicola.Domain.Galpon", null)
                        .WithMany()
                        .HasForeignKey("GalponId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FSH.Modules.Avicola.Domain.Lote", null)
                        .WithMany()
                        .HasForeignKey("LoteAnteriorId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("FSH.Modules.Avicola.Domain.RegistroAlimentacion", b =>
                {
                    b.HasOne("FSH.Modules.Avicola.Domain.Lote", null)
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("FSH.Modules.Avicola.Domain.RegistroMortalidad", b =>
                {
                    b.HasOne("FSH.Modules.Avicola.Domain.Lote", null)
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("FSH.Modules.Avicola.Domain.RegistroPeso", b =>
                {
                    b.HasOne("FSH.Modules.Avicola.Domain.Lote", null)
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("FSH.Modules.Avicola.Domain.RegistroSanitario", b =>
                {
                    b.HasOne("FSH.Modules.Avicola.Domain.Lote", null)
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
